apiVersion: v1
kind: Service
metadata:
  labels:
    app: hubot-irc
  name: hubot-irc
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hubot-irc
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
